### ISSUE TITLE
What kind of information is tracked by default

### ISSUE THREAD

**Issue by sunil-shrestha** [urbanairship/phonegap-ua-push#107]
Hi, we have a requirement to track some information about the device such as device-type, os version, location, language etc. So, just wondering what kind of information are tracked by this plugin and how can we inspect those information. Thanks in advance.

**Comment by rlepinski** [comment]
@sunil-shrestha 
We track device type, app version, os version, language by default. We only track location if location is enabled. Most of this information is exposed through our dashboards, the insight product, and connect.

How are you trying to use this information?

**Comment by sunil-shrestha** [comment]
Thanks for quick reply. We are using these information for general analytics purpose. In addition, we are also planning to use language information to send push notification in different languages. 

Do we need to request permission for location in the app or the plugin keeps track of when location is enabled?

**Comment by SeanyC** [comment]
@sunil-shrestha
You can find device information using [Device Property Tags](http://docs.urbanairship.com/reference/device-property-tags.html#location). Language and Locale tags are added here as well.

Regarding location in Cordova, the plugin does not add location permissions by itself, its up to your application to do that. The plugin does prompt for permission on both iOS and Android once everything is set up. Just need to enable location updates.
