### ISSUE TITLE
Incompatible with Firebase sdk as urbanaiship is using older version of Google Play Services i.e. 8.4.0

### ISSUE THREAD

**Issue by 96MayankJain** [urbanairship/phonegap-ua-push#108]
As Urban Airship is using 'com.google.android.gms:play-services-location:8.4.0' and also not compatible with 'com.google.android.gms:play-services-location:9.0.0' not able to integrate with Firebase in my project. Please suggest

**Comment by hcrowell** [comment]
Hi @96MayankJain , We plan to release our Android Urban Airship 7.2.0 SDK with Google Play Services updated to 9.x (soon), then we will update this plugin.

**Comment by 96MayankJain** [comment]
@hcrowell  What will be the ETA for this . Please let me know

**Comment by hcrowell** [comment]
Hi @96MayankJain , ETA is in the next few days. Will let you know when we update this plugin with our latest Android 7.2.0 SDK

**Comment by hcrowell** [comment]
@96MayankJain We just released the 5.3.0 plugin with our latest Android 7.2.0 SDK that uses Google Play services 9.0.2.

**Comment by 96MayankJain** [comment]
@hcrowell  Thanks for the update , we have implemented the same.
