### ISSUE TITLE
Typescript typings and ionic 2 support

### ISSUE THREAD

**Issue by joshgarwood** [urbanairship/phonegap-ua-push#109]
Hi there!

I am in the process of developing a new app in Ionic2 using Typescript. Given the well-defined structure of the UrbanAirship namespace, I was wondering if you have plans to create typings for Typescript to allow a nicely typed programming experience in Typescript.

I installed [these typings](https://github.com/retyped/urbanairship-cordova-tsd-ambient), but they don't seem to be recognized.  Any help leveraging UrbanAirship with typescript and Ionic 2 would be much appreciated.

Thanks for your time!

**Comment by rlepinski** [comment]
We do not have any immediate plans for Typescript and honestly I am not sure what that would look like in a cordova plugin. Could you point me to a plugin that provides typing but does not interfere with using the plugin without typescript?

**Comment by joshgarwood** [comment]
Hey @rlepinski !  Thanks so much for the quick reply!  Typescript typings are actually separate from the plugin itself.  There's a great library of types in this repo: https://github.com/DefinitelyTyped/DefinitelyTyped, which is awesome because it looks like someone has actually already added the typings for the Urban Airship plugin.  I'm starting to use it now and it seems to work well so far.

Thanks!

**Comment by jonathanwkelly** [comment]
@joshgarwood I am trying to get the custom types working with an Ionic 2 project. The `@types/urbanairship-cordova` seem to be compiled, as `UAirship` is no longer showing as undefined by the linter. However, I'm getting `can't find variable: UAirship` when I run in an emulator. Did you run into this issue? How was it resolved?

**Comment by denisonluz** [comment]
> @joshgarwood I am trying to get the custom types working with an Ionic 2 project. The `@types/urbanairship-cordova` seem to be compiled, as `UAirship` is no longer showing as undefined by the linter. However, I'm getting `can't find variable: UAirship` when I run in an emulator. Did you run into this issue? How was it resolved?

@jonathanwkelly Any solution for this?

I've noticed it only happens when using Windows. Exactly same code works fine on Mac.

**Comment by jonathanwkelly** [comment]
@denisonluz Not directly; I moved over to using OneSignal
