### ISSUE TITLE
Navigate user to certain page when notification is opened

### ISSUE THREAD

**Issue by sunil-shrestha** [urbanairship/phonegap-ua-push#110]
Hi, We are using this plugin with rails gem (https://github.com/urbanairship/ruby-library) in the backend. 
Currently, we have an application which gets push notifications for games and we want to take user to particular game page when notification is opened. 

Is there any easy way to handle this kind of event?

**Comment by rlepinski** [comment]
@sunil-shrestha It looks like the ruby library supports sending [deep links](http://docs.urbanairship.com/reference/libraries/ruby/3.2.3/push.html#actions) to the device. Once the deep link is sent, you can retrieve it from the plugin with [getDeepLink] ( http://docs.urbanairship.com/reference/libraries/urbanairship-cordova/latest/module-UrbanAirship.html#.getDeepLink). Let me know if it works for you.

**Comment by sunil-shrestha** [comment]
@rlepinski, Thanks for your quick response. 
I see that "getDeepLink" function returns the last received deep link. Wondering what happens when there are multiple notifications with different deep links. Also, i am still not clear when to call this function. Is there some kind of event triggered when notification is opened?

**Comment by rlepinski** [comment]
@sunil-shrestha The deep link is set when a notification that contains the deep link is tapped. Apps should check it on app start and when the app resumes.

**Comment by sunil-shrestha** [comment]
@rlepinski, Thanks for your help, it works 👍
