### ISSUE TITLE
Unable to retrieve the message list in Android & IOS both (Using Ionic-Angluar based platform)

### ISSUE THREAD

**Issue by 96MayankJain** [urbanairship/phonegap-ua-push#114]
How can I retrieve the Urban Airship message inbox from the Cordova plugin?

I have called this method **getInboxMessages** from **UrbanAirship.js**
UAirship.getInboxMessages(
    function (successobj) {console.log("success : " + JSON.stringify(successobj))},
    function (failureobj) {console.log("error : " + JSON.stringify(failureobj))}
);

Every time I am getting a **Blank Array** . I have already send three message to my devices and all message are received.But unable to retrieve.
![message-overview](https://cloud.githubusercontent.com/assets/4171272/16986201/ccea0b3c-4ea2-11e6-9e62-88932402424a.JPG)

@hcrowell Please help me out

**Comment by hcrowell** [comment]
@96MayankJain  You may be getting a blank array if the inbox is not ready yet. Try adding an event listener for `urbanairship.inbox_updated` and then call your `UAirship.getInboxMessages` code after the inbox has been updated.
ie. 
`var onInboxUpdate = function(event) {
      if (!event.error) {
        console.log("Inbox updated")
        // call UAirship.getInboxMessages
     })

 document.addEventListener("urbanairship.inbox_updated", onInboxUpdate, false)
`

**Comment by hcrowell** [comment]
Please contact support@urbanairship.com for any issues integrating or using this plugin. Thank you!

**Comment by 96MayankJain** [comment]
@hcrowell  Thanks its working now.
