### ISSUE TITLE
Disable push notifications on android in foreground

### ISSUE THREAD

**Issue by ant0ha** [urbanairship/phonegap-ua-push#115]
Hello! Can you please add some option to disable push notifications in foreground on android.

Related discussions:
https://support.urbanairship.com/entries/109222566-Handling-push-notification-on-Android-when-app-is-in-the-foreground-cordova-plugin-
https://github.com/urbanairship/phonegap-ua-push/issues/84

**Comment by ant0ha** [comment]
Will be great if we will be able to manage it from JS. For example on receiving event:

`
document.addEventListener('urbanairship.push', function (event) {
    if (!appPaused) {
        event.preventDefault();
    }
}, true);
`

**Comment by hcrowell** [comment]
Hi @ant0ha ! We currently do not support this, but accept pull requests! Please submit a PR and fill out & submit a Contribution Agreement http://docs.urbanairship.com/contribution-agreement.html . We will try to get back to you as soon as we can! Thank you!

**Comment by ant0ha** [comment]
@hcrowell thank you for answer, but it is not a decision.

1. I am not a Java developer and I can't fix this plugin.
2. This fix is very important for our app and managers think to change Push service. But we've spent much time for integration. 

Do you have any another ideas?

**Comment by ant0ha** [comment]
<img width="285" alt="config_xml_-_vm-desktop-app_-____work_vm-desktop-app_" src="https://cloud.githubusercontent.com/assets/787918/17096144/b07062b4-5260-11e6-94af-c2c4bded419c.png">

I see 4 files for the plugin. Can you pls help in which file/line should I disable pushes if app is not paused?

**Comment by ant0ha** [comment]
I've found decision and it is very simple!

```
            $ionicPlatform.ready(function () {
                if (window.UAirship && ionic.Platform.isAndroid()) {
                    UAirship.setUserNotificationsEnabled(false);

                    document.addEventListener('pause', function () {
                        UAirship.setUserNotificationsEnabled(true);

                        $log.debug('Push notifications: enabled');
                    });

                    document.addEventListener('resume', function () {
                        UAirship.setUserNotificationsEnabled(false);

                        $log.debug('Push notifications: disabled');
                    });
                }
            });
```

**Comment by rlepinski** [comment]
@ant0ha That will work, but if the app dies before you are able to re-enable user notifications then the application will not be able to display notifications in the background until the next app open.

I'll add an item to our backlog to introduce a flag for foreground notifications on Android. If you want to try to implement it yourself, you would need to [extend the default notification center](https://github.com/urbanairship/phonegap-ua-push/blob/master/src/android/CordovaAutopilot.java#L103) to return `null` instead of a notification if the app is in the foreground. We would want to make this configurable, so introduce a config setting in the config.xml.

Example code:
```
final boolean allowForegroundNotifications = pluginConfig.getBoolean(ALLOW_FOREGROUND_NOTIFICATIONS, true);

DefaultNotificationFactory factory = new DefaultNotificationFactory(context) {
    @Override
    public Notification createNotification(@NonNull PushMessage message, int notificationId) {
        if (!allowForegroundNotifications && UAirship.shared().getAnalytics().isAppInForeground()) {
            return null;
        }

        return super.createNotification(message, notificationId);
    }
};
```
