### ISSUE TITLE
EVENT "urbanairship.registration" not firing 

### ISSUE THREAD

**Issue by 7Style** [urbanairship/phonegap-ua-push#116]
I use cordova for my app.
in Xcode works everything
but in my javascript code can not get **ChanelD**.
because the events are not working.    

   `document.addEventListener("urbanairship.registration", function (event) {
                        console.log (event);

                        if (event.error) {
                            console.log('There was an error registering for push notifications')
                        } else {
                            console.log("Registered with ID: " + event.channelID)
                        }
                    });`

**Comment by hcrowell** [comment]
Hi @7Style , Please provide logs to debug this issue. Can you reproduce this issue using our https://github.com/urbanairship/phonegap-ua-push/tree/master/Example ? Thanks!

**Comment by 7Style** [comment]
Thank you for your reply.
I have solved the problem.
I had just re-install the plugin.

it works.
