### ISSUE TITLE
Need Guidance in Message center Styling in Android and IOS both

### ISSUE THREAD

**Issue by 96MayankJain** [urbanairship/phonegap-ua-push#118]
I am unable to change the header color and window background color of the message center.I need to customize these as of my application UI. I have developed the application in ionic-angular platform. I have a very less knowledge about android ios native code. @hcrowell  Please help me
Here is my messsagecenter style xml : 

<?xml version="1.0" encoding="utf-8"?>
<resources>
  <color name="searchrxheadercolor">#573689</color>
  <color name="searchrxwindowbgrcolor">#ffffff</color>

  <style name="MessageCenterAppTheme" parent="Widget.AppCompat.Light.ActionBar.Solid.Inverse">
    
    
    
    
    <item name="messageCenterStyle">@style/MessageCenterAppTheme.MessageCenter</item>
  </style>

  <style name="MessageCenterAppTheme.MessageCenter" parent="MessageCenter">
    <item name="messageCenterDividerColor">#44000000</item>
    <item name="messageCenterItemIconEnabled">false</item>
    <item name="bannerPrimaryColor">@color/searchrxheadercolor</item>
    <item name="messageCenterItemBackground">@color/searchrxheadercolor</item>
    <item name="messageCenterItemTitleTextAppearance">@style/MessageCenterAppTheme.MessageCenter.TitleTextAppearance</item>
    <item name="messageCenterItemDateTextAppearance">@style/MessageCenterAppTheme.MessageCenter.DateTextAppearance</item>
  </style>

  
  <style name="MessageCenterAppTheme.MessageCenter.TitleTextAppearance" parent="MessageCenter.Item.Title.TextAppearance">
    <item name="android:textSize">20sp</item>
    <item name="android:textStyle">italic</item>
    <item name="android:textColor">@android:color/black</item>
    <item name="urbanAirshipFontPath">"fonts/CustomFont.ttf"</item>
  </style>

  
  <style name="MessageCenterAppTheme.MessageCenter.DateTextAppearance" parent="MessageCenter.Item.Date.TextAppearance">
    <item name="android:textSize">16sp</item>
    <item name="android:textColor">@android:color/black</item>
    <item name="urbanAirshipFontPath">"fonts/CustomFont.ttf"</item>
  </style>
</resources>

I have attached a sample file , how do they managed to style the header color in the attached file?
![sample](https://cloud.githubusercontent.com/assets/4171272/17134420/ebe6a5f0-5347-11e6-85ed-9b3b83d92abb.png)

**Comment by 96MayankJain** [comment]
Also , Can we change the detail message page styling which comes after click on the listing page?Please let me know in detail. Thanks

**Comment by rlepinski** [comment]
Theming the provided message center is currently not supported. You may have better luck building the message center directly in html. You will have to modify the generated project or fork the plugin to do your own changes if you want a themed message center.

The style header for Android picks up the app themes color. You may want to replace https://github.com/urbanairship/phonegap-ua-push/blob/master/plugin.xml#L48 with the theme you are picking.

Please read these docs to see if they help:
http://docs.urbanairship.com/platform/android.html#message-center
http://docs.urbanairship.com/platform/ios.html#message-center 
http://docs.urbanairship.com/topic-guides/ios-message-center-customization.html
http://docs.urbanairship.com/topic-guides/android-rp-tutorial.html

**Comment by Carlosps** [comment]
Hi @rlepinski 

Any updates on that?

Is there anyway to customize the message center layout using the urbanairship-cordova plugin? I couldn't find anything in the https://docs.airship.com/platform/cordova/message-center/.

Thanks.
