### ISSUE TITLE
Can I get data from push notification when app is closed in iOS and app not running in background?

### ISSUE THREAD

**Issue by 96MayankJain** [urbanairship/phonegap-ua-push#119]

**Comment by 96MayankJain** [comment]
Hi Team,

**This is my code** 

`- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {

    if(application.applicationState == UIApplicationStateInactive) {

        NSLog(@"Inactive");

        //Show the view with the content of the push

        completionHandler(UIBackgroundFetchResultNewData);

    } else if (application.applicationState == UIApplicationStateBackground) {

        NSLog(@"Background");

        //Refresh the local model

        completionHandler(UIBackgroundFetchResultNewData);

    } else {

        NSLog(@"Active");

        //Show an in-app banner

        completionHandler(UIBackgroundFetchResultNewData);

    }
}
![bg-notification](https://cloud.githubusercontent.com/assets/4171272/17555949/30b3a6d6-5f2f-11e6-9ea5-757460a8be00.JPG)
`
I am not able to get logs when Notification comes and application is in closed or in background state. I had made the following settings (Screen Shot has been attached)

**Comment by rlepinski** [comment]
You need to send a notificaiton with content-available set to 1. Please contact support if you have further issues.
