### ISSUE TITLE
Notification icon not showing

### ISSUE THREAD

**Issue by sunil-shrestha** [urbanairship/phonegap-ua-push#127]
I have beein trying to get the notification icon working with an ionic app. It works fine with Android 4.x but with Nexus 6(Android 6.x) i am missing the icon on notification

Here is what i have set minSDKVersion and targetSdkVersion in config.xml file. Not sure if the path is not correct or something else. 

 ```
<preference name="com.urbanairship.notification_icon" value="drawable-ldpi/icon" />
<preference name="android-minSdkVersion" value="19"/>
<preference name="android-targetSdkVersion" value="23"/>
```

I would be thankful if someone could give an example with location of icon and path to icon we set in the config.xml file.

**Comment by rlepinski** [comment]
@sunil-shrestha its just the name of the icon, not the path. So if you have an icon in `drawable-ldpi/icon.png` the value should just be `icon`.
