### ISSUE TITLE
Receive notifications twice on IOS 9+

### ISSUE THREAD

**Issue by nickoj81** [urbanairship/phonegap-ua-push#129]
Hi,

I'm receiving all notification alerts twice on IOS 9+ devices. 

The notification is only showing once in the notification feed but the sound is played twice and  shows on the banner twice.

I've tried various combinations of enabling notifications thorough the config xml and the JS api but am only able to have no notifications or 2. When running the app in the foreground the notification event is only fired once. This behaviour is not apparent on Android or on a test device running IOS 8.

Thanks

**Comment by rlepinski** [comment]
Is the app foregrounded or backgrounded when you receive the notification. Can you provide logs? APNS posts the notification on behalf of the application, so depending on the state of the device its either the plugin code displaying the notification or APNS receiving duplicate notifications.

**Comment by rlepinski** [comment]
Is the app foregrounded or backgrounded when you receive the notification. Can you provide logs? APNS posts the notification on behalf of the application, so depending on the state of the device its either the plugin code displaying the notification or APNS receiving duplicate notifications.

**Comment by rlepinski** [comment]
Is the app foregrounded or backgrounded when you receive the notification. Can you provide logs? APNS posts the notification on behalf of the application, so depending on the state of the device its either the plugin code displaying the notification or APNS receiving duplicate notifications.

**Comment by teamsynced** [comment]
This is happening intermittently for me as well. Shows twice on the lock screen when sending to 1 device token.

**Comment by teamsynced** [comment]
This is happening intermittently for me as well. Shows twice on the lock screen when sending to 1 device token.

**Comment by teamsynced** [comment]
This is happening intermittently for me as well. Shows twice on the lock screen when sending to 1 device token.

**Comment by rlepinski** [comment]
This is a question for our support team and not a direct issue with the plugin. They are better at handling these types of issues than I am.
