### ISSUE TITLE
IOS 10 not registered device token

### ISSUE THREAD

**Issue by naitikpatel1990** [urbanairship/phonegap-ua-push#132]
I run app on IOS 10 and check in "device token" section but my device is not at all registered.

For IOS 9, i can see token is registered but "status" always remain "Inactive"

**Comment by rlepinski** [comment]
@naitikpatel1990 We will be releasing an update today with iOS 10 support.

**Comment by rlepinski** [comment]
Just released 6.0.0 https://www.npmjs.com/package/urbanairship-cordova

**Comment by naitikpatel1990** [comment]
after install plugin 6.0.0 i got following error at time of build IOS:

      **'UserNotifications/UserNotifications.h' file not found
#import <UserNotifications/UserNotifications.h>
        ^
1 error generated.

** BUILD FAILED ****

Please guide.

**Comment by hcrowell** [comment]
The latest Urban Airship PhoneGap/Cordova plugin 6.0.0 has been updated to support iOS 10 and thus requires Xcode 8. Please try with Xcode 8.

**Comment by naitikpatel1990** [comment]
I update latest Lib 6.0.0 and upgraded xcode 8.0 but still persisting same issue.

Also put question on [StackOverflow](http://stackoverflow.com/questions/39591589/urbanairship-ios-10-push-not-working)

Please guide

**Comment by rlepinski** [comment]
@naitikpatel1990 how are you determining you are not registering a device token? do you have any device logs?

**Comment by naitikpatel1990** [comment]
Through xcode's log i got to determine that i am not gettgin device token. 

I tried today without change any code, i got device token and it's working perfectly. That may be cache issue my side.

Also need to do following for getting push in IOS 10:

> 1) In the targets, under Capabilities enable Push Notifications to add Push Notifications Entitlements.
> 
> 2) Implement UserNotifications.framework into your app. Import UserNotifications.framework in your AppDelegate.
