### ISSUE TITLE
Release 6.0 - iOS Build Crash 

### ISSUE THREAD

**Issue by betorobson** [urbanairship/phonegap-ua-push#133]
Hi,

I have installed release 6.0 and it won't build anymore. Have a look at my fatal error:

Cordova version is update.
Xcode 7.3.1

`
In file included from /Users/roberto/Work/planyou/planyou-app/mobileApp/platforms/ios/Tissi/Plugins/urbanairship-cordova/UAPush.h:27:
/Users/roberto/Work/planyou/planyou-app/mobileApp/platforms/ios/Tissi/Plugins/urbanairship-cordova/UAirship.h:39:9: fatal error: 
      'UserNotifications/UserNotifications.h' file not found
#import <UserNotifications/UserNotifications.h>
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/Tissi.build/Debug-iphonesimulator/Tissi.build/Objects-normal/i386/UAirshipPlugin.o Tissi/Plugins/urbanairship-cordova/UAirshipPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/roberto/Work/planyou/planyou-app/mobileApp/platforms/ios/cordova/build-debug.xcconfig,-project,Tissi.xcodeproj,ARCHS=i386,-target,Tissi,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/roberto/Work/planyou/planyou-app/mobileApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/roberto/Work/planyou/planyou-app/mobileApp/platforms/ios/build/sharedpch
`

**Comment by hcrowell** [comment]
Hi @betorobson , the latest Urban Airship PhoneGap/Cordova plugin 6.0.0 has been updated to support iOS 10 and thus requires Xcode 8. Please try with Xcode 8.
