### ISSUE TITLE
iOS - Turn on Push Notification capabilities

### ISSUE THREAD

**Issue by betorobson** [urbanairship/phonegap-ua-push#136]
I believe that I found other issue.

The plugin should turn on Push Notification capabilities automatically on iOS project?

I had remove my iOS platform and added it again but this capability comes always turned off.
So, I have to manually turn it on. Have a look on my screenshot:

![screen shot 2016-09-20 at 2 23 10 pm](https://cloud.githubusercontent.com/assets/13212208/18681447/8dfdaa42-7f3e-11e6-99b8-97a79e83b579.png)

**Comment by rlepinski** [comment]
In previous versions of Xcode this was not needed.  I am not sure if its something that can be enabled by the plugin. Another thing for us to look at. Major Xcode updates are always painful.

**Comment by betorobson** [comment]
Yeah I know how is this updates. Apple has been keeping our jobs a live for a long time ago with this changes lol. 

In my tests, device can't get pushes without turn this capability on.

**Comment by rlepinski** [comment]
@betorobson Looks like it has to be a manual process. Ill try to update docs today. Thanks for the report.

**Comment by macdonst** [comment]
@rlepinski there is a commit to add the capability in cordova-ios 4.3.0 

https://github.com/apache/cordova-ios/pull/256

Then in plugin.xml you can add:

```
<config-file parent="aps-environment" target="*/Entitlements-Debug.plist">
          <string>development</string>
</config-file>
```

**Comment by rlepinski** [comment]
@macdonst Awesome. We will be sure to update as soon as its released.

**Comment by Bart-Holland** [comment]
So I am trying to make sense of this all.
In an app (Cordova 5.2.0 / cordova-iOS 4.2.0) I use phonegap-plugin-push 1.8.2 
in the plugin.xml I manually added under platform  ios:

```
<config-file parent="aps-environment" target="*/Entitlements-Debug.plist">
      <string>development</string>
</config-file>
<config-file parent="aps-environment" target="*/Entitlements-Release.plist">
      <string>production</string>
</config-file>
```

In the APP_Recourses I created a Entitlements-Debug.plist and a Entitlements-Release.plist 

Now running a debug version on my iPhone (iOS 10.0.2) I can recieve push notifications. 
However running a release (using testflight) I cannot recieve push notifications.

As I can't use xcode I seem to be stuck at creating these files myself.
Unfortunately I also can't upgrade my Cordova version. 

When I was running iOS 9, this all worked well.
anybody some ideas what is going wrong here?

**Comment by rlepinski** [comment]
@Bart-Holland Support for automatically enable push provision wont be released until Cordova 4.3.0, its still not released.

Xcode 7 had this capability switch but it was not a requirement for push to work. That is probably why it use to be fine in past releases.

**Comment by kkirby** [comment]
@rlepinski What's the status on this? I'm still not seeing Push Notifications enabled by default and Cordova is now at 6.x.x

**Comment by rlepinski** [comment]
@kkirby The capabilities seem to be working for us without modifying the xcode project. You still need to enable user notifications on the plugin as we do not do that by default (prompt the user for permission).

**Comment by sharonswli** [comment]
This is still an issue with cordova ios@4.5.4. Cannot get receive any push notification without going into xcode and manually turning on Push notifications in the Capabilities tab.

**Comment by Keepertje** [comment]
Same problem with cordova ios @4.5.5

**Comment by BrianBatchelder** [comment]
@sharonswli : Please [open a new ticket](https://github.com/urbanairship/urbanairship-cordova/issues/new) with details of your setup and the issue you are seeing. Thank you.
