### ISSUE TITLE
Badge count not decrement and but removed 

### ISSUE THREAD

**Issue by naitikpatel1990** [urbanairship/phonegap-ua-push#141]
I have issue in IOS badge decrement one. On push arrived badge is increment every time. Suppose, i have 5 notification pending in notification list and badge count is 5 now, when i opened one of any notification from 5 that time badge count become 0 and removed and other 4 notification also flush out.

**Comment by rlepinski** [comment]
@naitikpatel1990 Try setting `com.urbanairship.clear_badge_onlaunch` to false in your config and see if that helps.

**Comment by naitikpatel1990** [comment]
i tried that but it's clear all badges, suppose i have 5 notifications count and 5 notification , i open one of 5 notifications it's clear badge and also removed badge also gone.

I need to do if i open one notification count should be 5 - 1 = 4 and notifications also remain 4 , and if i click another one count should be 4-1 = 3 and remain 3 notifications 3 which untouched, and so on.

for more info please go through my [StackOverflow question](http://stackoverflow.com/questions/39632491/ios-push-decrement-badge-on-push-open-in-urbanairship-push?noredirect=1#comment66634166_39632491)

**Comment by rlepinski** [comment]
Could you decrement the badge count yourself when you detect a launch from push using getBadgeNumber and setBadgeNumber?

**Comment by naitikpatel1990** [comment]
yes i mange count, but if i remove push from notification window count won't remove..

**Comment by rlepinski** [comment]
@naitikpatel1990 iOS 10 added a way to get the current notifications in the notification center - https://developer.apple.com/reference/usernotifications/unusernotificationcenter/1649520-getdeliverednotifications prior to iOS 10, this was impossible.

The badge is not suppose to correspond to how many notifications are in the notificaiton center, but rather how many in-app messages/updates are waiting for the user.

**Comment by naitikpatel1990** [comment]
ok then, i'll manage badge from server side, Thank you.
