### ISSUE TITLE
crashing in android when i start the app

### ISSUE THREAD

**Issue by ituhin** [urbanairship/phonegap-ua-push#152]
crash started after i added this plugin... earlier i was using phonegap-plugin-push ... at first i tried both together but didnot work... so i removed phonegap-PushPlgin.. but still no luck

ionic info --
Cordova CLI: 6.4.0
Ionic Framework Version: 1.1.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

cordova platform
  android 6.0.0

cordova plugins
com.lampa.startapp 0.1.4 "startApp"
com.verso.cordova.clipboard 0.1.0 "Clipboard"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-whitelist 1.2.0 "Whitelist"
cordova-plugin-x-socialsharing 5.0.7.1 "SocialSharing"
cordova-plugin-x-toast 2.3.1 "Toast"
cordova.plugins.diagnostic 2.3.11 "Diagnostic"
de.appplant.cordova.common.registerusernotificationsettings 1.0.1 "RegisterUserNotificationSettings"
de.appplant.cordova.plugin.badge 0.7.1 "Cordova Badge Plugin"
ionic-plugin-keyboard 1.0.8 "Keyboard"
urbanairship-cordova 6.2.0 "Urban Airship"

in my config.xml 
    preference name="android-minSdkVersion" value="19"
    preference name="android-targetSdkVersion" value="23"

crash log ---
10-31 17:55:33.549 18591 18617 I Drop A Coin - UALib: Airship taking off!
10-31 17:55:33.549 18591 18617 I Drop A Coin - UALib: Airship log level: 3
10-31 17:55:33.550 18591 18617 I Drop A Coin - UALib: UA Version: 8.0.1 / App key = IA_y_DjSRTiuGbQMWnD6EQ Production = false
10-31 17:55:33.566 18591 18591 I CordovaLog: Changing log level to DEBUG(3)
10-31 17:55:33.567 18591 18591 I CordovaActivity: Apache Cordova native platform version 6.0.0 is starting
10-31 17:55:33.567 18591 18591 D CordovaActivity: CordovaActivity.onCreate()
10-31 17:55:33.579 18591 18591 I WebViewFactory: Loading com.google.android.webview version 54.0.2840.68 (code 284006800)
10-31 17:55:33.655 18591 18617 D Drop A Coin - UALib: Analytics - New session: 0ffdb3de-f322-4bb5-a20a-a8eccdc09900
10-31 17:55:33.664 18591 18617 I Drop A Coin - UALib: Airship ready!
.............................
.............................
--------- beginning of crash
10-31 17:55:34.626 18591 18666 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
10-31 17:55:34.626 18591 18666 E AndroidRuntime: Process: com.bitscorp.dac, PID: 18591
10-31 17:55:34.626 18591 18666 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method areNotificationsEnabled()Z in class Landroid/support/v4/app/NotificationManagerCompat; or its super classes (declaration of 'android.support.v4.app.NotificationManagerCompat' appears in /data/app/com.bitscorp.dac-1/base.apk)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.push.PushManager.isOptIn(PushManager.java:491)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.push.PushManager.getNextChannelRegistrationPayload(PushManager.java:503)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.push.ChannelJobHandler.onUpdateChannelRegistration(ChannelJobHandler.java:327)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.push.ChannelJobHandler.performJob(ChannelJobHandler.java:161)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:326)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at com.urbanairship.AirshipService$1.run(AirshipService.java:168)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-31 17:55:34.626 18591 18666 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)

in project.properties file
target=android-24
android.library.reference.1=CordovaLib
cordova.system.library.1=com.facebook.android:facebook-android-sdk:4.14.+
cordova.system.library.2=com.google.android.gms:play-services-analytics:+
cordova.system.library.3=com.android.support:support-v4:23.+
cordova.system.library.4=com.android.support:appcompat-v7:23.+
cordova.gradle.include.1=de.appplant.cordova.plugin.badge/dac-badge.gradle
cordova.gradle.include.2=urbanairship-cordova/dac-build-extras.gradle

i tried adding this in build-extras.gradle... but no luck
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:23.4.0'
    }
}

**Comment by rlepinski** [comment]
UA SDK 8.0 requires support-v4 24+. Looks like its pulling in 23. Try removing the force resolution strategy bit and update your android SDK.

**Comment by rlepinski** [comment]
Please reopen if you continue to have issues.
