### ISSUE TITLE
iOS urbanairship.push event not firing when app is in background

### ISSUE THREAD

**Issue by sonulaugh** [urbanairship/phonegap-ua-push#153]
I saw the code & cannot see anywhere iOS is responding to urbanairship.push event. This only works if the app is in foreground. 

The app need to react once the notification arrives, this works well in android but not in iOS as the app is in background. This event is attached to fetch new content in javascript.
Can anybody help?

**Comment by rlepinski** [comment]
How are you sending the push? In order for the app to wake up from the event you have to send it with "content-available" set to 1. 

I am not sure if the JS environment will be loaded to receive that event. Good luck and let me know how things go!

**Comment by sonulaugh** [comment]
Can we get some pending events & fire them when app gets resume event fired? I can send "content-available" from REST service but I doubt my JS environment may not be alive. Want to trigger something on next app launch. Do you have any API already handling all this?

**Comment by rlepinski** [comment]
@sonulaugh We currently do not support that behavior. Could you provide details on how you would use it? 

If you are trying to send content down with the push, you might want to rethink that approach and instead do a push to pull type system. Background push is not very consistent in iOS.

**Comment by sonulaugh** [comment]
We are trying to sync data whenever a notification arrived. The urbanairship.notification_opened fires when ever we cliked the notification. The sync goes well. But if the notification arrives & user clicks the App icon the sync is not triggering. 

Can we track the notification is pushed & in the subsequent launch will fire an event?

**Comment by rlepinski** [comment]
Notifications can be up to 4k in size, and we can have an unknown number of them. It would take significant work to keep all of the notifications ready and then we might overload the app once its able to handle them. 

Background push is not meant to be used in this way. Instead you should have a known URL that the app can check on foreground to sync the data.
