### ISSUE TITLE
Dismissing inbox message display

### ISSUE THREAD

**Issue by davidgovea** [urbanairship/phonegap-ua-push#162]
Hello UA team -- this plugin has been working out very nicely for us, thank you!

Since the message center cannot be styled in the phonegap plugin, we have implemented our own inbox display in HTML. We are then using `displayInboxMessage()` to show the native message display, and deep-link actions inside the rich message to navigate within our platform.

The `deep_link` event is working great, but I would like to dismiss the message display while handling the deep link. A `dismissInboxMessage()` or even a one-shot `closeAll()` method that dismisses the message center and any inbox messages would be very handy.

Thanks for your time -- let me know if I've missed something in the docs!
-David

**Comment by hcrowell** [comment]
Hi @davidgovea , Glad to hear the plugin has been working out for you. Please contact `support@urbanairship.com` with this feature request, so that we can prioritize it in our back log. Thank you!

**Comment by hcrowell** [comment]
Reopening this issue for status updates on this feature request.

**Comment by rlepinski** [comment]
@davidgovea We are working on this now, its just proving to be a bit more difficult then we anticipated. We hope to have something for you to try out soon.

**Comment by davidgovea** [comment]
Thanks for the update @rlepinski!

**Comment by hcrowell** [comment]
@davidgovea We just released 6.6.0 with this feature request!
We've added the following methods: `dismissMessageCenter()`, `dismissInboxMessage()` and `dismissOverlayInboxMessage()`

**Comment by davidgovea** [comment]
👍  :1st_place_medal:👍 
Thank you! -- about to pull down the new release now --
