### ISSUE TITLE
iOS problem: fatal error: 'AirshipLib.h' file not found

### ISSUE THREAD

**Issue by githubjameshenderson** [urbanairship/phonegap-ua-push#174]
I have been using this plugin successfully in the last few weeks but now I get:

fatal error: 'AirshipLib.h' file not found

Is anyone else getting this when compiling for iOS?

**Comment by rlepinski** [comment]
@githubjameshenderson We recently switched to using pod support provided by cordova when bundling our iOS SDK. 

From our README:

> This plugin uses cocoapods which is supported in cordova-ios 4.3.0. Ensure cocoapods is installed and the pod repo is updated via pod repo update. If using Xcode directly, open the xcworkspace instead of the xcodeproj.

Are you using the `xcworkspace` instead of `xcdoeproj` to open your project?

**Comment by githubjameshenderson** [comment]
Thanks Ryan - it is working for me now

**Comment by rlepinski** [comment]
Awesome. Glad it works.

**Comment by jskrepnek** [comment]
Hi @rlepinski:

I'm getting a very similar error from Phonegap Build.  Can't reproduce locally.  We're using phonegap-version cli-6.5.0 which is associated with cordova-ios 4.3.1.

We're using version 6.6.0 of the urbanairship-cordova plugin.  I haven't tried updating yet.

Here's a snippet from the log:

```
dhweolsvbwrgoyeypmnbrhvoqwcp/Build/Intermediates/ArchiveIntermediates/KohoAlpha/IntermediateBuildFilesPath/KohoAlpha.build/Release-iphoneos/KohoAlpha.build/Objects-normal/armv7/UAirshipPlugin.o
In file included from /project/KohoAlpha/Plugins/urbanairship-cordova/UAirshipPlugin.m:26:
/project/KohoAlpha/Plugins/urbanairship-cordova/UAirshipPlugin.h:28:9: fatal error: 'AirshipLib.h' file not found
#import "AirshipLib.h"
        ^
```

The most recent change is the additional of the phonegap-plugin-push plugin.

Thanks for any help.

**Comment by rlepinski** [comment]
@jskrepnek We moved away from cocoapods in 6.7 due to various cordova integration issues. Updated should fix your issues.
