### ISSUE TITLE
Android: can't seem to build

### ISSUE THREAD

**Issue by bz123** [urbanairship/phonegap-ua-push#175]
I am using the latest version of cordova and latest android sdk.

I've included version 16+ for android.

This is the error message I get.

Any ideas?

(I get it only when urbanairship is installed)

`Running command: /Users/user/Desktop/go/mobile/hooks/after_prepare/010_add_platform_class.js /Users/user/Desktop/go/mobile
add to body class: platform-android
Running command: /Users/user/Desktop/go/mobile/hooks/after_prepare/020_remove_sass_from_platforms.js /Users/user/Desktop/go/mobile
Running command: /Users/user/Desktop/go/mobile/hooks/after_prepare/ionic-minify.js /Users/user/Desktop/go/mobile
ANDROID_HOME=/Users/user/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders
:CordovaLib:compileDebugShaders
:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:incrementalDebugJavaCompilationSafeguard
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preReleaseBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders
:CordovaLib:compileReleaseShaders
:CordovaLib:generateReleaseAssets
:CordovaLib:mergeReleaseAssets
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:incrementalReleaseJavaCompilationSafeguard
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportCardviewV72510Library
:prepareComAndroidSupportSupportCompat2510Library
:prepareComAndroidSupportSupportCoreUi2510Library
:prepareComAndroidSupportSupportCoreUtils2510Library
:prepareComAndroidSupportSupportFragment2510Library
:prepareComAndroidSupportSupportMediaCompat2510Library
:prepareComAndroidSupportSupportV42510Library
:prepareComGoogleAndroidGmsPlayServicesBase1001Library
:prepareComGoogleAndroidGmsPlayServicesBasement1001Library
:prepareComGoogleAndroidGmsPlayServicesGcm1001Library
:prepareComGoogleAndroidGmsPlayServicesIid1001Library
:prepareComGoogleAndroidGmsPlayServicesLocation1001Library
:prepareComGoogleAndroidGmsPlayServicesTasks1001Library
:prepareComUrbanairshipAndroidUrbanairshipSdk825Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
/Users/user/Desktop/go/mobile/platforms/android/AndroidManifest.xml:49:9-59:20 Warning:
        activity#com.urbanairship.cordova.CustomLandingPageActivity was tagged at AndroidManifest.xml:49 to replace another declaration but no other declaration present
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.214 secs
Error: /Users/user/Desktop/go/mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
`

**Comment by ralepinski** [comment]
No idea whats going on here. Could you try to update your Android SDK and try again?

**Comment by bz123** [comment]
Android project updated with cordova-android@6.1.2


and all my SDKS are up to date, still crashing on the same thing.

**Comment by rlepinski** [comment]
Can you cd into the android directory and run `./gradlew clean` and provide the output of the dependency by running `./gradelw app:dependencies` and debug build output `./gradlew build --debug` ?

It looks like you have 2 versions of `com/google/android/gms/actions/ReserveIntents` which is causing the build issue. What other plugins do you have installed? Maybe one of them is including a jar of google play services?

**Comment by bz123** [comment]
here is the list of my plugins:

com.telerik.plugins.nativepagetransitions 0.6.2 "Native Page Transitions"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-google-analytics 0.7.1 "Google Universal Analytics Plugin"
cordova-plugin-googleplayservices 19.0.1 "Google Play Services for Android"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"
urbanairship-cordova 6.6.0 "Urban Airship"


as you can see I have a plugin googleplayservices but its needed for my google analytics

**Comment by rlepinski** [comment]
@bz123 That plugin is problematic. It is including a jar of Google Play Services so it will cause conflicts for every plugin that pulls in Google Play Services as a dependency. https://github.com/floatinghotpot/google-play-services/tree/master/libs/google-play-services_lib/libs.

Do you only need that plugin for `cordova-plugin-google-analytics` ? If so it looks like its no longer required - https://github.com/danwilson/google-analytics-plugin/blob/master/plugin.xml#L54

**Comment by rlepinski** [comment]
If that does not work you can use https://cordova.apache.org/docs/en/latest/guide/platforms/android/#extending-buildgradle to add your own dependencies for google play services and remove the usage of the problematic `cordova-plugin-googleplayservices` plugin.

**Comment by bz123** [comment]
Thank you I'll close this issue for now as it seems to be due to other dependancies and try to resolve it, thanks for your help.
