### ISSUE TITLE
iOS Build fails if plugin isn't last one added

### ISSUE THREAD

**Issue by kkirby** [urbanairship/phonegap-ua-push#178]
Building iOS will fail with:

```
ld: warning: directory not found for option '-L/Users/kkirbatski/Library/Developer/Xcode/DerivedData/HelloCordova-epislepkvkacgnaoqycxnydtpcul/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK'
ld: library not found for -lUrbanAirship-iOS-SDK
```

if the plugin is not the last plugin added.

I can't find a consistent way to get cordova to install the urbanairship plugin not last, but I've noticed that it happens and when it does this error occurs on build.

**Comment by rlepinski** [comment]
@kkirby How are you building it? Through xcode or cordova cli?

**Comment by kkirby** [comment]
cordovacli, though the same issues happens via Xcode. Cordova appears to add the plugins in a non-specific order. But whenever this plugin is not the last one added, that error comes up upon building.

**Comment by kkirby** [comment]
Though, going off of the plugin.xml of this plugin, it seems more like a bug with cordova and not with this plugin. Thoughts?

**Comment by rlepinski** [comment]
ryan.lepinski@urbanairship.com

Could you give me your cordova cli, ios-plugin, and ua plugin versions?

**Comment by kkirby** [comment]
@rlepinski I sent you an email.

**Comment by rlepinski** [comment]
@kkirby I was able to reproduce the issue. This is looking more and more like a cordova issue that we should report. Still looking into it.

**Comment by rlepinski** [comment]
@kkirby Yeah, cordova issue. I can't figure out any automatic workarounds other than to stop using cocoapods. Could you post a issue on https://issues.apache.org ? I am having troubles recovering my account.

**Comment by kkirby** [comment]
@rlepinski [Done](https://issues.apache.org/jira/browse/CB-12582)
