### ISSUE TITLE
adding build.json using phonegap build

### ISSUE THREAD

**Issue by thurt** [urbanairship/phonegap-ua-push#187]
Hi,

I'm trying to figure out how to add step 4 of setup:

```
 {
     "ios": {
         "debug": {
             "developmentTeam": "XXXXXXXXXX"
         },
         "release": {
             "developmentTeam": "XXXXXXXXXX"
         }
     }
 }
```

I am using PhoneGap Build and wondering how this is added ? phonegap build basically only has a `config.xml` file

Thanks for any info

**Comment by rlepinski** [comment]
@hurt here are the cordova docs on that feature - https://cordova.apache.org/docs/en/latest/guide/platforms/ios/#using-buildjson

**Comment by rlepinski** [comment]
Updated the README with a link to the cordova docs.
