### ISSUE TITLE
value for com.urbanairship.notification_icon

### ISSUE THREAD

**Issue by thurt** [urbanairship/phonegap-ua-push#190]
I don't understand what values can be substituted for `ic_notification` in the com.urbanairship.notification_icon rule in the `config.xml`. 

Can I supply a path to an image? Does the value start at a particular folder?

**Comment by rlepinski** [comment]
@thurt It needs to be the name of a drawable that ends up in your android's resource directory. It looks like you define the icons using resource-file in the config.xml: https://cordova.apache.org/docs/en/latest/config_ref/index.html#resource-file
