### ISSUE TITLE
Programatically turn on/off in_production feature

### ISSUE THREAD

**Issue by saurabhgupta050890** [urbanairship/phonegap-ua-push#196]
Is it possible to turn of the in_production flag from JavaScript part ? 

Currently its done using, <preference name="com.urbanairship.in_production" value="true | false" /> in config file. 

We need to keep separate builds for production and development.

**Comment by crow** [comment]
@saurabhgupta050890 Unfortunately, toggling the in_production status of your application can't be accomplished through the javascript interface. The JS interface doesn't load quickly enough to modify the SDK configuration.
