### ISSUE TITLE
Notifications Buttons & Deep Links

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#199]
Is there any possible way to access Deep Link or Notification Buttons data ?

**Comment by rlepinski** [comment]
@gonzalovinas You can access the deep link through the event. We currently do not expose what notification button was clicked but would easily be added.

**Comment by rlepinski** [comment]
Added `actionID` and `isForeground` to the notification open event in 6.9.3. Should give you the info you need to determine what button was tapped.

**Comment by gonzalovinas** [comment]
Awesome gift! Thanks


*Gonzalo Viñas*
Signature powered by
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>
WiseStamp
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>
