### ISSUE TITLE
Change App/Secret Keys programatically/runtime

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#200]
I 'm developing an APP which at start needs a QR Code scan to know to which server (Customer Backoffice) has to connect to. That works well :-) now I need Push Notifications  work the same way.  I need someway to change the Keys.

You think Is possible?

Solution A: add a mes cool method exposed to JS interface and make the magic happens, but ist that possible at all ?

 
Solution B: write file/db (frontera JS) row when switching Customer Backoffice, then switching keys, then notify the user the need to Erstattung App/Device ? Any Channel ID issues at sight ? and modify Plugin to read from File/DB row instead from propierties File.

**Comment by marc-scig** [comment]
I'm afriad this isn't supported. The SDK doesn't allow for multiple takeoffs, so the key and secret are effectively fixed for the runtime lifecycle of the app. There are potentially other ways of solving your problem, though, depending on what you're trying to do. For instance, you can use tags, named users, and other segmentation features to programmatically control groups of users that can receive different notifications. I'd recommend checking out the docs (https://docs.urbanairship.com/engage/target-specific-users) to start with.

**Comment by gonzalovinas** [comment]
My problem is business. I'm looking for a way to detach Customers (my clients and their users) form ISV (myself) in regards to urbanairship membership.

**Comment by rlepinski** [comment]
@gonzalovinas In order to support this request would require significant refactoring in our SDKs. Could you provide more details on a flow so we can help you come up with an alternative? Maybe deferring takeOff in the App is a potential workaround?

**Comment by gonzalovinas** [comment]
My client is an ISV. They have customers A, B and C. This ISV develops/sells a Backoffice. I will develop an single APP for all their customers. When the APP starts it ask to read a QR Code with backoffice server address embedded to connect to.

Push Notifications need to work exactly the same way. Customers A, B and C nowadays work onpremise or by collocation in the public internet. I would like customers A, B and C have their own urbanairship membership and not to let the ISV be in the middle of any resource for their production line except for the software, but TRUE is UA KEYs are per membership, so they NEED to be set at APP SETUP somehow..

Does it sound clear for you? Am I way out of place designing UA services like that?

**Comment by rlepinski** [comment]
It make sense, its just not a common use case or one that we ever had to support. Do you support reconfiguring the app after the first QR code scanning? How often does this happen?

**Comment by gonzalovinas** [comment]
Its a possibilty. A/B testing is a general case, but rarely for Production/Real users. Whats' in your mind?

**Comment by rlepinski** [comment]
It would be significantly easier to modify this plugin to delay takeOff until after the user scans the QR code. Each subsequent app launches would need to call takeOff right away after its configured. Allowing an app to change config mid run will still be problematic. You could do it, but the UA instance would not update until the next app launch.

**Comment by gonzalovinas** [comment]
It will work for me! is that possible with the current version? I could fork a branch and make the need updates to the code for you... I need these changes in cordova and reactnative.

**Comment by rlepinski** [comment]
@gonzalovinas are you building a single app that uses both? 

It wont work with the current plugins, they will have to be modified. Its not super trivial but I can provide some guidance. The general steps would be:
- Enable delaying takeOff with some sort of config flag
- Add takeOff call to the plugin, should take the app key/secret
- Persist the appkey/secret in nsuserdefaults/shared preferences
- Have the plugin call takeOff right away on app start if the config is available
- Make the plugin interface return an empty result/error if takeOff is not called yet

**Comment by rlepinski** [comment]
@gonzalovinas https://github.com/urbanairship/urbanairship-cordova/pull/236 & https://github.com/urbanairship/urbanairship-cordova/pull/235 enable calling takeOff in the JS layer, making it possible to delay the initial takeOff.

**Comment by gonzalovinas** [comment]
Update to version 7.2.0 for testing this delayed takeOff feature!!
