### ISSUE TITLE
Where to find development app key and secret?

### ISSUE THREAD

**Issue by newuser44** [urbanairship/phonegap-ua-push#201]
I'm guessing this is documented somewhere, I just don't know where else to ask this. 

In the config.xml we put in the following. 
<preference name="com.urbanairship.production_app_key" value="Your Production App Key" />
 <preference name="com.urbanairship.production_app_secret" value="Your Production App Secret" />
 <preference name="com.urbanairship.development_app_key" value="Your Development App Key" />
 <preference name="com.urbanairship.development_app_secret" value="Your Development App Secret" />

I don't know how to find those items?  I think I have gotten the production app key and secret but what about development?

**Comment by rlepinski** [comment]
Development is just another app that you can create within the dashboard. Its optional. For questions like these, please contact Urban Airship support.
