### ISSUE TITLE
Silent Notifications

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#202]
Is this feature supported ? Thanks!

**Comment by rlepinski** [comment]
Could you explain what you mean by silent notifications ? Notifications that do not make sound or a data push that does not display a notification?

**Comment by gonzalovinas** [comment]
:) the second one those that display nothing at all


*Gonzalo Viñas*
Signature powered by
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>
WiseStamp
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>

**Comment by rlepinski** [comment]
We do support sending data only pushes. Our plugin will generate a push received event when received. However I believe Cordova's context will only be loaded when the app is foregrounded, so you might only be able to receive those pushes when the app is in the foreground.
