### ISSUE TITLE
Android GCM registation Id

### ISSUE THREAD

**Issue by jskrepnek** [urbanairship/phonegap-ua-push#205]
Hi,

Is it possible to get access to the underlying GCM/FCM registration Id in additional to the channel Id, upon registration?

Thanks.

**Comment by rlepinski** [comment]
@jskrepnek Currently no, but it would be an easy addition. We can add it to the event in the next release.

**Comment by jskrepnek** [comment]
Great, thanks @rlepinski.

**Comment by rlepinski** [comment]
Added to 6.9.3
