### ISSUE TITLE
Production PUSH not working

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#207]
I've created PROD Distro Certificate to publish to AppStore via TestFlight. My App is working but not receiving PUSH notifications neither foreground nor background.

But it does when deployed via usb cable from xCode. 

So... I've check APS enviroment, App Keys/Secrets but urbanairship console error says device token rejected.

Airshipconfig.plis is set to inProduction = TRUE... what else should I need to take a look ?

I've been 2 and a half full days bumbling💃 

I'm using cordova 7.1.0 and cordova-ios 4.5.1 and xcode 9.1

**Comment by rlepinski** [comment]
It could be a lot of things. Please contact support, they will be able to guide you through troubleshooting. APNS cert issues are a pain.

**Comment by gonzalovinas** [comment]
Thanks, I'll remove this message, since its urbans topic no matter
integration API targets..


*Gonzalo Viñas*
Signature powered by
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>
WiseStamp
<http://r1.wisestamp.com/r/landing?u=f2fb39b70c4ca423&v=2.4.4.0&t=1309824053813&promo=0&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_0>

**Comment by gonzalovinas** [comment]
not a cordova issue
