### ISSUE TITLE
Channel ID not changing after re-instalation on iPhone

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#219]
When I uninstall/re-install my APP on Android, channel id changes, but sometimes on some iphones it doesn´t.

Ring any bell to you this behaviour?

Thanks in advance!

**Comment by BrianBatchelder** [comment]
This behavior is as expected. The channel id may or may not change after re-install.

**Comment by gonzalovinas** [comment]
But current documentation says:

_The Channel ID is a unique identifier that ties together an application/device pair on a mobile devices. The Channel ID is used to target pushes to specific devices using the Urban Airship API. Once a Channel ID is created, it will persist the application until it is either reinstalled, or its internal data is cleared._

**Comment by BrianBatchelder** [comment]
@gonzalovinas - That documentation is not very clear. We'll get it updated.

On iOS, the channel ID may or may not change after re-install. Currently, the Android channel id ID changes after every re-install, but we could change that at any time. The important thing is not to count on the channel ID changing (or not changing) on re-install.
