### ISSUE TITLE
Deep Link on resume state

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/phonegap-ua-push#220]
I know deep_link event works just fine when the APP is on Foreground or Background but not when resumes o start from scratch.

Have any plans on supporting this feature? kind of **latest_deep_link**? 

I think it could be implemented saving the data somewhere inside the android activity or the delegate on ios. 

What do you think?

**Comment by rlepinski** [comment]
Could you elaborate on why its not working when its cold start? Missing the event?

We already have https://docs.urbanairship.com/reference/libraries/urbanairship-cordova/latest/module-UrbanAirship.html#.getDeepLink that you can probably use for latest deep link.
