### ISSUE TITLE
Creating a custom category

### ISSUE THREAD

**Issue by pbirsinger** [urbanairship/phonegap-ua-push#221]
I want to make notifications with custom buttons (e.g. "Play" and "Save for later"), but to do that it appears I need to register a new custom category as per the documentation:

```
let categoryAction = UANotificationAction(identifier: "category_action",
                                               title: "Action!",
                                             options: [.authenticationRequired, .foreground, .destructive])
// Define the category
let category = UANotificationCategory(identifier: "custom_category",
                                         actions: [categoryAction],
                               intentIdentifiers: [],
                   hiddenPreviewsBodyPlaceholder: "Sensitive Content Hidden",
                                         options: [])
// Set the custom categories
UAirship.push().customCategories = [category]
// Update registration
UAirship.push().updateRegistration()
```

Does this plugin support this at all yet?

**Comment by rlepinski** [comment]
This plugin does not support custom categories at the moment. Right now you will either have to modify the generated iOS/Android project directly or fork this plugin to do that for you.

**Comment by pbirsinger** [comment]
@rlepinski thanks for the update. Are there any future plans to add custom categories?

**Comment by ralepinski** [comment]
@pbirsinger We currently do not have any plans, but its a valid request so I will add it to our backlog. No idea on timing.

The hard part around custom categories is we need to know them during takeOff to ensure they are available when a push is received on Android and they need to be persisted so we do not override them on iOS. So we either will have to save them and expose a add/remove call in JS or make it possible to define them with xml/plist as config. Do you use phonegap build?

**Comment by rlepinski** [comment]
@pbirsinger We currently do not have any plans, but its a valid request so I will add it to our backlog. No idea on timing.

The hard part around custom categories is we need to know them during takeOff to ensure they are available when a push is received on Android and they need to be persisted so we do not override them on iOS. So we either will have to save them and expose a add/remove call in JS or make it possible to define them with xml/plist as config. Do you use phonegap build?

**Comment by pbirsinger** [comment]
@rlepinski appreciate you slotting it into your backlog. To build, we run "cordova build ios" and then build again on xcode.

Defining them in the config.xml would be perfect for us. We really just need a way to customize the buttons' names and have them go to custom deep links.

**Comment by rlepinski** [comment]
I would be interested it knowing how they do that. To clear the badge you have to set the [applicationiconbadgenumber](https://developer.apple.com/documentation/uikit/uiapplication/1622918-applicationiconbadgenumber) property on UIApplication. Our API that we expose in our plugin basically is a direct call to that API.

Looks like someone had success setting it to [-1](https://forums.developer.apple.com/thread/7598),  but that seems to [not work anymore](https://stackoverflow.com/questions/37789581/clear-applicationiconbadgenumber-without-removing-notifications-not-working/41758039#41758039). Looks like some other people have hacky workarounds in that thread.

**Comment by marc-scig** [comment]
Closing this for now.

**Comment by rlepinski** [comment]
@pbirsinger https://github.com/urbanairship/urbanairship-cordova/pull/228 is the PR for this request. It will be released in the next major version of this plugin.
