### ISSUE TITLE
resetBadge clearing notifications?

### ISSUE THREAD

**Issue by pbirsinger** [urbanairship/phonegap-ua-push#223]
Not sure if I am doing something wrong, but calling both resetBadge and setBadgeNumber(0) clears all notifications for me. It seems that this is not intentional, as there is a separate clearNotifications func.

Is this a bug, and if not, is there a way to clear the badge but preserve notifications?

I'm only testing on ios if it helps.

**Comment by pbirsinger** [comment]
Thanks for the quick reply @rlepinski. So presently there's no way around that? I just ask because I notice that other apps are able to clear the badge but preserve notifications, but maybe it's just a cordova thing (classic).

**Comment by rlepinski** [comment]
I would be interested it knowing how they do that. To clear the badge you have to set the [applicationiconbadgenumber](https://developer.apple.com/documentation/uikit/uiapplication/1622918-applicationiconbadgenumber) property on UIApplication. Our API that we expose in our plugin basically is a direct call to that API.

Looks like someone had success setting it to [-1](https://forums.developer.apple.com/thread/7598),  but that seems to [not work anymore](https://stackoverflow.com/questions/37789581/clear-applicationiconbadgenumber-without-removing-notifications-not-working/41758039#41758039). Looks like some other people have hacky workarounds in that thread.

(Posted on wrong issue originally)
