### ISSUE TITLE
Plugin crashes when a push notification is received before user notifications are enabled

### ISSUE THREAD

**Issue by ccaleb** [urbanairship/phonegap-ua-push#286]
# Preliminary Info

### What version of urbanairship-cordova are you using?
v7.5.0

### Is your issue affecting the Android platform, iOS platform, or both?
Android

### What version of cordova-ios and/or cordova-android are you using?
cordova-cli: 8.1.2
cordova-android: 7.0.0

# Report

### What unexpected behavior are you seeing?
My application crashes when a push notification is sent from the Urban Airship dashboard. At this point the Urban Airship plugin has been initialised within my app but user notifications have not yet been explicitly enabled.

### What is the expected behavior?
I would expect the app to ignore any incoming push notifications (and not crash) since user notifications have, at this point, not yet been enabled.

### What are the steps to reproduce the unexpected behavior?
1. Install the Urban Airship plugin via npm.

2. Add a reference to my google-services.json file in the app's config.xml

3. Within my code, initialise the Urban Airship plugin:
UAirship.takeOff(keysObject);
UAirship.setAndroidNotificationConfig({
    icon: "ic_notification",
    largeIcon: "ic_notification_large",
    accentColor: "#FF0000"
});

3. Build and launch the app.

4. Once the app is running, create a message within the Urban Airship dashboard. Send the message.

### Some additional information
The app behaves as expected once I explicitly enable user notifications by calling:

UAirship.setUserNotificationsEnabled(true);

However, I don't want my users to receive notifications until they have opted-in, which is why initially my app runs with user notifications disabled.

As mentioned above, everything works as expected once user notifications are explicitly enabled - the device receives any notifications sent from the UA dashboard. However, I allow users at a later date to switch off notifications via a settings menu. When this is done, I once again disable notifications via the setUserNotificationsEnabled() method. At this point, the app once again crashes the next time messages are sent from the UI dashboard.

### Do you have logging for the issue?
The app crashes at this line within the plugin's PushEvent.java file:

data.putOpt("notificationId", getNotificationdId(notificationId, notificationTag));

Both notificationId and notificationTag are null, which leads to a crash directly within the getNotificationdId() method when it tries to convert notificationId to a string.

When user notifications are enabled, the same point in the code succeeds because, this time, notificationId is non-null.

[log.txt](https://github.com/urbanairship/urbanairship-cordova/files/2824334/log.txt)

**Comment by rlepinski** [comment]
Looks like it was introduced 7.4.0. We will have this fixed today.
