### ISSUE TITLE
Any way to disable the notification when the app is in foreground: Android?

### ISSUE THREAD

**Issue by coomar2841** [urbanairship/phonegap-ua-push#84]
I have integrated the plugin, and it works fine. The JS callbacks are triggered when there's an incoming push when the app is in the foreground.

But, I also need to avoid/disable the default notification when the app is in the foreground, since I would be showing the user a prompt asking him to interact with the message. 

How can that be achieved?

**Comment by ant0ha** [comment]
Hi! I am not a java developer. Can you pls explain how to disable push notifications for android in foreground mode?

**Comment by ant0ha** [comment]
You can found workaround here: #115
